# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:            date
paginate_path:        /page:num
relative_permalinks:  true

# Setup
title:            'Jeffrey W. Hollister'
tagline:          ''
description:      'Landscape Ecology, Lakes, GIS, R, and Open Science'
url:              http://jwhollister.com
baseurl:          /

author:
  name:           'Jeffrey W. Hollister'
  url:            https://twitter.com/jhollist

paginate:         5

timezone:         America/New_York

# Custom vars
version:          0.2.0

logos:
  - site:     https://twitter.com/jhollist
    img:      https://g.twimg.com/Twitter_logo_blue.png
  - site:     https://impactstory.org/JeffreyHollister/
    img:      https://impactstory.org/static/img/impactstory-logo-no-type.png   
  - site:     http://scholar.google.com/citations?user=Fn9BjfIAAAAJ&hl=en
    img:      https://impactstory.org/static/img/favicons/google_scholar.ico
  - site:     https://github.com/jhollist
    img:      http://www.iconsdb.com/icons/preview/white/github-10-xxl.png

github:
  repo:           

#Plugins
gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap