title:        'Jeffrey W. Hollister'
tagline:      ''
description:  'Landscape Ecology, Lakes, GIS, R, and Open Science'
url:          http://jwhollister.com
version:      0.0.1
author:
  name:       'Jeffrey W. Hollister'
  email:      'hollister.jeff@epa.gov'
markdown:     rdiscount
permalink:    pretty
highlighter:  pygments
paginate:     5
discuss:      true
