# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            'Jeffrey W. Hollister'
tagline:          ''
description:      'Landscape Ecology, Lakes, GIS, R, and Open Science'
url:              http://jwhollister.com
baseurl:          /

author:
  name:           'Jeffrey W. Hollister'
  url:            https://twitter.com/jhollist

paginate:         5

# Custom vars
version:          0.2.0

logos:
  - site:     https://twitter.com/jhollist
    img:      https://g.twimg.com/Twitter_logo_blue.png
  - site:     https://impactstory.org/JeffreyHollister/
    img:      http://i2.wp.com/impactstory.files.wordpress.com/2014/01/new-impactstory-logo-no-type1.png?resize=181%2C181     
  - site:     http://scholar.google.com/citations?user=Fn9BjfIAAAAJ&hl=en
  - site:     https://github.com/jhollist

github:
  repo:           

#Plugins
gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap