# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            'Jeffrey W. Hollister'
tagline:          ''
description:      'Landscape Ecology, Lakes, GIS, R, and Open Science'
url:              http://jwhollister.com
baseurl:          /

author:
  name:           'Jeffrey W. Hollister'
  url:            https://twitter.com/jhollist

paginate:         5

# Custom vars
version:          0.2.0

logos:
  - site:     https://twitter.com/jhollist
    img:      https://impactstory.org/static/img/favicons/twitter.ico
  - site:     https://impactstory.org/JeffreyHollister/
    img:      https://impactstory.org/static/img/favicon.ico    
  - site:     http://scholar.google.com/citations?user=Fn9BjfIAAAAJ&hl=en
    img:      https://impactstory.org/static/img/favicons/google_scholar.ico
  - site:     https://github.com/jhollist
    img:      https://impactstory.org/static/img/favicons/github.ico

github:
  repo:           

#Plugins
gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap