# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            'Jeffrey W. Hollister'
tagline:          ''
description:      'Landscape Ecology, Lakes, GIS, R, and Open Science'
url:              http://jwhollister.com
baseurl:          /

author:
  name:           'Jeffrey W. Hollister'
  url:            https://twitter.com/jhollist

paginate:         5

# Custom vars
version:          0.0.1

github:
  repo:           https://github.com/jhollist/jhollist.github.io
