# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            'Jeffrey W. Hollister'
tagline:          ''
description:      'Landscape Ecology, Lakes, GIS, R, and Open Science'
url:              http://jwhollister.com
baseurl:          /

author:
  name:           'Jeffrey W. Hollister'
  url:            https://twitter.com/jhollist

paginate:         5

# Custom vars
version:          0.2.0

logos:
  - site:     https://twitter.com/jhollist
    img:      https://g.twimg.com/Twitter_logo_blue.png
  - site:     https://impactstory.org/JeffreyHollister/
    img:      http://gravatar.com/avatar/9387b461360eaf54e3fa3ce763c656f4/?s=120&d=mm     
  - site:     http://scholar.google.com/citations?user=Fn9BjfIAAAAJ&hl=en
    img:      http://scholar.google.com/favicon.ico
  - site:     https://github.com/jhollist
    img:      http://demo.phalconeye.com/files/github.gif

github:
  repo:           

#Plugins
gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap